name: Python Unit Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.10 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests with pytest
        run: pytest --cov=backend --cov-report=term-missing backend/tests
